server:
  error:
    include-stacktrace: on-trace-param
  port: 8085
spring:
  application:
    name: admin-server
 
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  