eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
 

server:
  port: 9097
spring:
  application:
    name: apigateway-server
  cloud:    gateway:      discovery:        locator:          enabled: true
          lower-case-service-id: true
          
management:
  endpoints:
    web:
      exposure:
        include: '*'    

      

