server:
  error:
    include-stacktrace: on-trace-param
  port: 9093
spring:
  application:
    name: category-service
 
  datasource:
     password: ${RDS_PASSWORD:root}
     url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:microservices}
     username: ${RDS_USERNAME:root}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      
  zipkin:
    base-url: http://localhost:9411

     
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
management:
   endpoint:
    health:
      show-details: always
      
   endpoints:
    web:
      exposure:
        include: '*'